// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJSJ7pw-SwOk1Netbh9CmACuBm83x-YU',
    appId: '1:308613082441:web:2e014a68ddec461009fe98',
    messagingSenderId: '308613082441',
    projectId: 'able-pottery-241209',
    authDomain: 'able-pottery-241209.firebaseapp.com',
    storageBucket: 'able-pottery-241209.firebasestorage.app',
    measurementId: 'G-0ZKGPXEJSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY27aQjBT9oriVbUIaKoZCDQeR1U3Xfgw',
    appId: '1:308613082441:android:12d2a5aee05aad7c09fe98',
    messagingSenderId: '308613082441',
    projectId: 'able-pottery-241209',
    storageBucket: 'able-pottery-241209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG_RfAbfrfMZ6iZ7hkphB80L8eZxvz6Lk',
    appId: '1:308613082441:ios:9b09f92bb508a3ef09fe98',
    messagingSenderId: '308613082441',
    projectId: 'able-pottery-241209',
    storageBucket: 'able-pottery-241209.firebasestorage.app',
    iosBundleId: 'com.salimbaskoy.treadom',
  );
}
